runOn:
  - minServerVersion: "4.1.10"
database_name: &database_name "default"
collection_name: &collection_name "default"

data:
  - &doc0
    _id: 1
    encrypted_string:
      $binary:
        base64: {{ ciphertext("string1", field="encrypted_string")["$binary"]["base64"] }}
        subType: "00"
  - _id: 2
    encrypted_string:
      $binary:
        base64: "AQ=="
        subType: "06"
  - _id: 3
    encrypted_string:
      $binary:
        base64: "AQAAa2V2aW4gYWxiZXJ0c29uCg=="
        subType: "06"

# Since test requires invalid data to be inserted, use a local schema.
key_vault_data: [{{key()}}]

tests:
  - description: "Wrong subtype"
    clientOptions:
      autoEncryptOpts:
        schemaMap:
          "default.default": {{ schema() }}
        kmsProviders:
          aws: {} # Credentials filled in from environment.
    operations:
      - name: find
        arguments:
          filter: { _id: 1 }
        result:
          # gets returned without decryption
          - *doc0
  - description: "Empty data"
    clientOptions:
      autoEncryptOpts:
        schemaMap:
            "default.default": {{ schema() }}
        kmsProviders:
          aws: {} # Credentials filled in from environment.
    operations:
      - name: find
        arguments:
          filter: { _id: 2 }
        result:
          errorContains: "malformed ciphertext"
  - description: "Malformed data"
    clientOptions:
      autoEncryptOpts:
        schemaMap:
          "default.default": {{ schema() }}
        kmsProviders:
          aws: {} # Credentials filled in from environment.
    operations:
      - name: find
        arguments:
          filter: { _id: 3 }
        result:
          # ciphertext can only validate subtype (which is correct)
          # but takes the 16 byte UUID to look up key. Fails to find.
          errorContains: "did not provide all keys"